//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAP4.ClienteLibros.LibrosService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Libros", Namespace="http://schemas.datacontract.org/2004/07/DAP4.Biblioteca.Dominio")]
    [System.SerializableAttribute()]
    public partial class Libros : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string autor_nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string genero_nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_libroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int libro_anio_publicacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string libro_isbnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string libro_nombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string autor_nombre {
            get {
                return this.autor_nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.autor_nombreField, value) != true)) {
                    this.autor_nombreField = value;
                    this.RaisePropertyChanged("autor_nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string genero_nombre {
            get {
                return this.genero_nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.genero_nombreField, value) != true)) {
                    this.genero_nombreField = value;
                    this.RaisePropertyChanged("genero_nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_libro {
            get {
                return this.id_libroField;
            }
            set {
                if ((this.id_libroField.Equals(value) != true)) {
                    this.id_libroField = value;
                    this.RaisePropertyChanged("id_libro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int libro_anio_publicacion {
            get {
                return this.libro_anio_publicacionField;
            }
            set {
                if ((this.libro_anio_publicacionField.Equals(value) != true)) {
                    this.libro_anio_publicacionField = value;
                    this.RaisePropertyChanged("libro_anio_publicacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string libro_isbn {
            get {
                return this.libro_isbnField;
            }
            set {
                if ((object.ReferenceEquals(this.libro_isbnField, value) != true)) {
                    this.libro_isbnField = value;
                    this.RaisePropertyChanged("libro_isbn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string libro_nombre {
            get {
                return this.libro_nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.libro_nombreField, value) != true)) {
                    this.libro_nombreField = value;
                    this.RaisePropertyChanged("libro_nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LibrosService.ILibrosService")]
    public interface ILibrosService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibrosService/ObtenerLibroPorId", ReplyAction="http://tempuri.org/ILibrosService/ObtenerLibroPorIdResponse")]
        DAP4.ClienteLibros.LibrosService.Libros ObtenerLibroPorId(int id_libro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibrosService/ObtenerLibroPorId", ReplyAction="http://tempuri.org/ILibrosService/ObtenerLibroPorIdResponse")]
        System.Threading.Tasks.Task<DAP4.ClienteLibros.LibrosService.Libros> ObtenerLibroPorIdAsync(int id_libro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibrosService/ObtenerLibroPorNombre", ReplyAction="http://tempuri.org/ILibrosService/ObtenerLibroPorNombreResponse")]
        DAP4.ClienteLibros.LibrosService.Libros ObtenerLibroPorNombre(string libro_nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibrosService/ObtenerLibroPorNombre", ReplyAction="http://tempuri.org/ILibrosService/ObtenerLibroPorNombreResponse")]
        System.Threading.Tasks.Task<DAP4.ClienteLibros.LibrosService.Libros> ObtenerLibroPorNombreAsync(string libro_nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibrosService/ListarLibros", ReplyAction="http://tempuri.org/ILibrosService/ListarLibrosResponse")]
        DAP4.ClienteLibros.LibrosService.Libros[] ListarLibros();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibrosService/ListarLibros", ReplyAction="http://tempuri.org/ILibrosService/ListarLibrosResponse")]
        System.Threading.Tasks.Task<DAP4.ClienteLibros.LibrosService.Libros[]> ListarLibrosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibrosService/InsertarLibro", ReplyAction="http://tempuri.org/ILibrosService/InsertarLibroResponse")]
        void InsertarLibro(string libro_nombre, string libro_isbn, int anio_publicacion, string autor_nombre, string genero_nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibrosService/InsertarLibro", ReplyAction="http://tempuri.org/ILibrosService/InsertarLibroResponse")]
        System.Threading.Tasks.Task InsertarLibroAsync(string libro_nombre, string libro_isbn, int anio_publicacion, string autor_nombre, string genero_nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibrosService/ActualizarLibro", ReplyAction="http://tempuri.org/ILibrosService/ActualizarLibroResponse")]
        DAP4.ClienteLibros.LibrosService.Libros ActualizarLibro(int id_libro, string libro_nombre, string libro_isbn, int anio_publicacion, string autor_nombre, string genero_nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibrosService/ActualizarLibro", ReplyAction="http://tempuri.org/ILibrosService/ActualizarLibroResponse")]
        System.Threading.Tasks.Task<DAP4.ClienteLibros.LibrosService.Libros> ActualizarLibroAsync(int id_libro, string libro_nombre, string libro_isbn, int anio_publicacion, string autor_nombre, string genero_nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibrosService/EliminarLibro", ReplyAction="http://tempuri.org/ILibrosService/EliminarLibroResponse")]
        DAP4.ClienteLibros.LibrosService.Libros EliminarLibro(int id_libro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibrosService/EliminarLibro", ReplyAction="http://tempuri.org/ILibrosService/EliminarLibroResponse")]
        System.Threading.Tasks.Task<DAP4.ClienteLibros.LibrosService.Libros> EliminarLibroAsync(int id_libro);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILibrosServiceChannel : DAP4.ClienteLibros.LibrosService.ILibrosService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LibrosServiceClient : System.ServiceModel.ClientBase<DAP4.ClienteLibros.LibrosService.ILibrosService>, DAP4.ClienteLibros.LibrosService.ILibrosService {
        
        public LibrosServiceClient() {
        }
        
        public LibrosServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LibrosServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LibrosServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LibrosServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public DAP4.ClienteLibros.LibrosService.Libros ObtenerLibroPorId(int id_libro) {
            return base.Channel.ObtenerLibroPorId(id_libro);
        }
        
        public System.Threading.Tasks.Task<DAP4.ClienteLibros.LibrosService.Libros> ObtenerLibroPorIdAsync(int id_libro) {
            return base.Channel.ObtenerLibroPorIdAsync(id_libro);
        }
        
        public DAP4.ClienteLibros.LibrosService.Libros ObtenerLibroPorNombre(string libro_nombre) {
            return base.Channel.ObtenerLibroPorNombre(libro_nombre);
        }
        
        public System.Threading.Tasks.Task<DAP4.ClienteLibros.LibrosService.Libros> ObtenerLibroPorNombreAsync(string libro_nombre) {
            return base.Channel.ObtenerLibroPorNombreAsync(libro_nombre);
        }
        
        public DAP4.ClienteLibros.LibrosService.Libros[] ListarLibros() {
            return base.Channel.ListarLibros();
        }
        
        public System.Threading.Tasks.Task<DAP4.ClienteLibros.LibrosService.Libros[]> ListarLibrosAsync() {
            return base.Channel.ListarLibrosAsync();
        }
        
        public void InsertarLibro(string libro_nombre, string libro_isbn, int anio_publicacion, string autor_nombre, string genero_nombre) {
            base.Channel.InsertarLibro(libro_nombre, libro_isbn, anio_publicacion, autor_nombre, genero_nombre);
        }
        
        public System.Threading.Tasks.Task InsertarLibroAsync(string libro_nombre, string libro_isbn, int anio_publicacion, string autor_nombre, string genero_nombre) {
            return base.Channel.InsertarLibroAsync(libro_nombre, libro_isbn, anio_publicacion, autor_nombre, genero_nombre);
        }
        
        public DAP4.ClienteLibros.LibrosService.Libros ActualizarLibro(int id_libro, string libro_nombre, string libro_isbn, int anio_publicacion, string autor_nombre, string genero_nombre) {
            return base.Channel.ActualizarLibro(id_libro, libro_nombre, libro_isbn, anio_publicacion, autor_nombre, genero_nombre);
        }
        
        public System.Threading.Tasks.Task<DAP4.ClienteLibros.LibrosService.Libros> ActualizarLibroAsync(int id_libro, string libro_nombre, string libro_isbn, int anio_publicacion, string autor_nombre, string genero_nombre) {
            return base.Channel.ActualizarLibroAsync(id_libro, libro_nombre, libro_isbn, anio_publicacion, autor_nombre, genero_nombre);
        }
        
        public DAP4.ClienteLibros.LibrosService.Libros EliminarLibro(int id_libro) {
            return base.Channel.EliminarLibro(id_libro);
        }
        
        public System.Threading.Tasks.Task<DAP4.ClienteLibros.LibrosService.Libros> EliminarLibroAsync(int id_libro) {
            return base.Channel.EliminarLibroAsync(id_libro);
        }
    }
}
