//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAP4.ClienteLibros.EmpleadosService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Empleados", Namespace="http://schemas.datacontract.org/2004/07/DAP4.Biblioteca.Dominio")]
    [System.SerializableAttribute()]
    public partial class Empleados : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string empleado_apellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string empleado_cargoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string empleado_emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime empleado_fecha_nacField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string empleado_nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string empleado_telefonoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_empleadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string empleado_apellido {
            get {
                return this.empleado_apellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.empleado_apellidoField, value) != true)) {
                    this.empleado_apellidoField = value;
                    this.RaisePropertyChanged("empleado_apellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string empleado_cargo {
            get {
                return this.empleado_cargoField;
            }
            set {
                if ((object.ReferenceEquals(this.empleado_cargoField, value) != true)) {
                    this.empleado_cargoField = value;
                    this.RaisePropertyChanged("empleado_cargo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string empleado_email {
            get {
                return this.empleado_emailField;
            }
            set {
                if ((object.ReferenceEquals(this.empleado_emailField, value) != true)) {
                    this.empleado_emailField = value;
                    this.RaisePropertyChanged("empleado_email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime empleado_fecha_nac {
            get {
                return this.empleado_fecha_nacField;
            }
            set {
                if ((this.empleado_fecha_nacField.Equals(value) != true)) {
                    this.empleado_fecha_nacField = value;
                    this.RaisePropertyChanged("empleado_fecha_nac");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string empleado_nombre {
            get {
                return this.empleado_nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.empleado_nombreField, value) != true)) {
                    this.empleado_nombreField = value;
                    this.RaisePropertyChanged("empleado_nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string empleado_telefono {
            get {
                return this.empleado_telefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.empleado_telefonoField, value) != true)) {
                    this.empleado_telefonoField = value;
                    this.RaisePropertyChanged("empleado_telefono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_empleado {
            get {
                return this.id_empleadoField;
            }
            set {
                if ((this.id_empleadoField.Equals(value) != true)) {
                    this.id_empleadoField = value;
                    this.RaisePropertyChanged("id_empleado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EmpleadosService.IEmpleadosService")]
    public interface IEmpleadosService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpleadosService/ListarEmpleados", ReplyAction="http://tempuri.org/IEmpleadosService/ListarEmpleadosResponse")]
        DAP4.ClienteLibros.EmpleadosService.Empleados[] ListarEmpleados();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpleadosService/ListarEmpleados", ReplyAction="http://tempuri.org/IEmpleadosService/ListarEmpleadosResponse")]
        System.Threading.Tasks.Task<DAP4.ClienteLibros.EmpleadosService.Empleados[]> ListarEmpleadosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpleadosService/ObtenerEmpleadosPorId", ReplyAction="http://tempuri.org/IEmpleadosService/ObtenerEmpleadosPorIdResponse")]
        DAP4.ClienteLibros.EmpleadosService.Empleados ObtenerEmpleadosPorId(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpleadosService/ObtenerEmpleadosPorId", ReplyAction="http://tempuri.org/IEmpleadosService/ObtenerEmpleadosPorIdResponse")]
        System.Threading.Tasks.Task<DAP4.ClienteLibros.EmpleadosService.Empleados> ObtenerEmpleadosPorIdAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpleadosService/ObtenerEmpleadosPorApellido", ReplyAction="http://tempuri.org/IEmpleadosService/ObtenerEmpleadosPorApellidoResponse")]
        DAP4.ClienteLibros.EmpleadosService.Empleados ObtenerEmpleadosPorApellido(string apellido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpleadosService/ObtenerEmpleadosPorApellido", ReplyAction="http://tempuri.org/IEmpleadosService/ObtenerEmpleadosPorApellidoResponse")]
        System.Threading.Tasks.Task<DAP4.ClienteLibros.EmpleadosService.Empleados> ObtenerEmpleadosPorApellidoAsync(string apellido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpleadosService/InsertarEmpleados", ReplyAction="http://tempuri.org/IEmpleadosService/InsertarEmpleadosResponse")]
        DAP4.ClienteLibros.EmpleadosService.Empleados InsertarEmpleados(DAP4.ClienteLibros.EmpleadosService.Empleados empleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpleadosService/InsertarEmpleados", ReplyAction="http://tempuri.org/IEmpleadosService/InsertarEmpleadosResponse")]
        System.Threading.Tasks.Task<DAP4.ClienteLibros.EmpleadosService.Empleados> InsertarEmpleadosAsync(DAP4.ClienteLibros.EmpleadosService.Empleados empleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpleadosService/ActualizarEmpleado", ReplyAction="http://tempuri.org/IEmpleadosService/ActualizarEmpleadoResponse")]
        DAP4.ClienteLibros.EmpleadosService.Empleados ActualizarEmpleado(DAP4.ClienteLibros.EmpleadosService.Empleados empleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpleadosService/ActualizarEmpleado", ReplyAction="http://tempuri.org/IEmpleadosService/ActualizarEmpleadoResponse")]
        System.Threading.Tasks.Task<DAP4.ClienteLibros.EmpleadosService.Empleados> ActualizarEmpleadoAsync(DAP4.ClienteLibros.EmpleadosService.Empleados empleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpleadosService/EliminarEmpleado", ReplyAction="http://tempuri.org/IEmpleadosService/EliminarEmpleadoResponse")]
        bool EliminarEmpleado(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpleadosService/EliminarEmpleado", ReplyAction="http://tempuri.org/IEmpleadosService/EliminarEmpleadoResponse")]
        System.Threading.Tasks.Task<bool> EliminarEmpleadoAsync(string id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEmpleadosServiceChannel : DAP4.ClienteLibros.EmpleadosService.IEmpleadosService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmpleadosServiceClient : System.ServiceModel.ClientBase<DAP4.ClienteLibros.EmpleadosService.IEmpleadosService>, DAP4.ClienteLibros.EmpleadosService.IEmpleadosService {
        
        public EmpleadosServiceClient() {
        }
        
        public EmpleadosServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmpleadosServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmpleadosServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmpleadosServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public DAP4.ClienteLibros.EmpleadosService.Empleados[] ListarEmpleados() {
            return base.Channel.ListarEmpleados();
        }
        
        public System.Threading.Tasks.Task<DAP4.ClienteLibros.EmpleadosService.Empleados[]> ListarEmpleadosAsync() {
            return base.Channel.ListarEmpleadosAsync();
        }
        
        public DAP4.ClienteLibros.EmpleadosService.Empleados ObtenerEmpleadosPorId(string id) {
            return base.Channel.ObtenerEmpleadosPorId(id);
        }
        
        public System.Threading.Tasks.Task<DAP4.ClienteLibros.EmpleadosService.Empleados> ObtenerEmpleadosPorIdAsync(string id) {
            return base.Channel.ObtenerEmpleadosPorIdAsync(id);
        }
        
        public DAP4.ClienteLibros.EmpleadosService.Empleados ObtenerEmpleadosPorApellido(string apellido) {
            return base.Channel.ObtenerEmpleadosPorApellido(apellido);
        }
        
        public System.Threading.Tasks.Task<DAP4.ClienteLibros.EmpleadosService.Empleados> ObtenerEmpleadosPorApellidoAsync(string apellido) {
            return base.Channel.ObtenerEmpleadosPorApellidoAsync(apellido);
        }
        
        public DAP4.ClienteLibros.EmpleadosService.Empleados InsertarEmpleados(DAP4.ClienteLibros.EmpleadosService.Empleados empleado) {
            return base.Channel.InsertarEmpleados(empleado);
        }
        
        public System.Threading.Tasks.Task<DAP4.ClienteLibros.EmpleadosService.Empleados> InsertarEmpleadosAsync(DAP4.ClienteLibros.EmpleadosService.Empleados empleado) {
            return base.Channel.InsertarEmpleadosAsync(empleado);
        }
        
        public DAP4.ClienteLibros.EmpleadosService.Empleados ActualizarEmpleado(DAP4.ClienteLibros.EmpleadosService.Empleados empleado) {
            return base.Channel.ActualizarEmpleado(empleado);
        }
        
        public System.Threading.Tasks.Task<DAP4.ClienteLibros.EmpleadosService.Empleados> ActualizarEmpleadoAsync(DAP4.ClienteLibros.EmpleadosService.Empleados empleado) {
            return base.Channel.ActualizarEmpleadoAsync(empleado);
        }
        
        public bool EliminarEmpleado(string id) {
            return base.Channel.EliminarEmpleado(id);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarEmpleadoAsync(string id) {
            return base.Channel.EliminarEmpleadoAsync(id);
        }
    }
}
